rna = 'ATGACTGTATTCGACTATGGTACTCCAGCGTACATCTTGTTGCAGGGAGTGTTCTGGATAAACGCCTACCCGAACAGTCAGTGCGTAACGCCTCATAAGCAGATCTAAACATAGGCATAACGCGGACAAATCTCGGAGGAACTCCAGCCAGACGTTCCGAGTAGTGTGTTGCCCAGCAACCAAAACAAGGCATGAGGGTGTATTCCGCGGCGAACAAAGGTGCCGGGTATGAGCAAAGGTGCAGGTTTTAAGTTTCATGCATAAGAGGTATGTGTGTCCGGTTATTAAAGTTCACGTGCGCATAACGACATGCCTTCCTAGCGCGTATCCCCGCAGCCGAGGCTTGGAACCCGACGGCAGGGATTTTGCTTAGAGCGGTTGGTTCAGACCGAAAAGGCGTGGTCCGCAGCTTCGCTACTTGAAACTTATGCTGCCAAACGGCTCGAGCGCTAGCTGAGCACAGCCTAACAGTTAGTGGAAAAGCGAAGTAGTGAGGAGTAACTCTGACTAACTGTATTCAATTAGATACGGGATGCAAGAGTACTGAAAAATCACTTGGGTCGGTAAAGTAAGGTTGCGCGCTCATTTCGCCAGGGGAGCTCGGGTGAGCTGTTAGAGTCTCTCAGAGGTCTATTCGCGAGGAGAGTCCAGGCCGCACAGCGCGCGCCGAAGAACCATACACCACACTCTTACACATAACCTTCAGTCCTCGTCCTGCTTTATAGATGTATTGTCGCGCTAAAATTCGCCCGAACTATTCTGCCCCAACAGTGAGGGACATTTTCTTAGAATTGCAGCCTGAGTACTTAAGGTAGCGCTGGGCTATGACGCGGCTTTGGCATATGAGTCCTAAGCGAGTAGTCTGTTTGAAAAGGTACAGACTCGAACAAAGCGTGTGGCTATTTAGCAAAGAATTAGCGTTTTTCGGGGGAACCACGAGTCGAATTATCCTCGTGTATTAGACAGTCGGCG'[::-1]
new_rna = ''
for nucleotide in rna:
    if nucleotide == 'T':
        new_rna += 'A'
    if nucleotide == 'C':
        new_rna += 'G'
    if nucleotide == 'A':
        new_rna += 'T'    
    if nucleotide == 'G': 
        new_rna += 'C'


print(new_rna)
