dna = 'TATCAGCATACATGCCCCGCACTACGTCAACGAGCGTAAAGCACTCGTTCTGACCGGTTTCACGTGTGCGCGCCCGGGAAGTGAGGCCGATGCTGTCGACAAAGTCCACGGTAACCTGCCGGAAGCTCTGATAGTGCGGTCAGATATCTCCTCGAACTGACACTTCAACTCACGGACTCGAGGCAATACTGCAGAGCCGTCTATCCCAATCTTGTTACTAGAATGCGACGACGAGAAGGTCGCCAGGGAAGGCAAGTAGTAGTATCACCTAGCTGATCAAGCCCAGGGGAAAAGACACATACAATACCCAGCTATTATTGACATTGTCCTCTCTCTGATTCGCATACTTTAAGCTGATCAATCTAGGGCACAATCAGGTAGATTCAGGTCGTTTGTGGTTCTCAAGCTCAGGGGTCTTGAGTGGTTAACAGTCGTCTTACTCGTCAAAATAGCAGTCCATTTCCGTATTCTTGTCAGACAAGGTGCAAACTAAAAACAAGACATAGCTTTTTTTCGTGTGTCTGAGACGAGGTCCTTCCTGTAGGTCGGGACGGTCTTGCCTCCGCGGGACCGGTGCATCGATCTCATTGGAGCTAATCCAGTCACTTTGGGGCCTTCCACCGTTAGTGGTCACTTACTGCCGTGGAAATGGACGATAAGGTTTGTTAAACCCGATCACGCAATTATAACAGCGCATGGTACCTTATGTAGAAACCGGTCCGTTAACAATCGGGCGCTGATTGCCGCCACACATGATATCCTGGAAAGTAATGTCGACGACGTGCGCCTATTCCGAATTCATCGTCCGGCCTGTGAAATTTGTCACTCCTTAAGCGTAATTAAAGGTCGGAGCCGGATCATTACACGTGACTGACAGGGATGTCACTCACGTAAACCAGCCACATCCACATAGGAGCCTCTGGGCGCATGGGTCAATCGCGGACCGGGTTCAATTAATTACTGGAAGCAGGAGTATGGTCTATTTAGAATAAGT'
A = 0
T = 0
G = 0
C = 0
for nucleotide in dna:
    if nucleotide == 'A':
        A += 1
    if nucleotide == 'T':
        T += 1
    if nucleotide == 'C':
        C += 1
    if nucleotide == 'G':
        G += 1

print(A,C,G,T)
print(len(dna))