from operator import index

dnaS = 'GGAGATATGCGCCGCTTACCGCTCAGACTTACGCTCTATGTGCTCACACCGACCCTATCCCTAAAAGACTCGATAAAGAACCGCCTCGGGAGCTACCAGTCACTCAATACGTTACTTTCGCGCTGACGCGTTTTAATCAATTTCTTGTTTCGGTTCGGACCGTTACGGCTGTCCTAGGGTCGAGCTTGTACGCAAGTGAGTGTGGTACGATGTTACAATCACGGCGCCGTGGCGGGCAGAGCAATGCTGACCTCCGCCAAAGAACAGAAGCCGATCTGGGGGGATCAACTCTAACCAGCCTGATTCCTTATTCCGGAAAATTTTGTATGGGGCCTTAATGCATGCCTCCCGGCCGACGTCGGCCGGGTATTTTATTCTTCGAGTTGAGCGAAACTAACCTATCATTGGGGAGCCGCAAGATTGTCAGGTAACGACTCTCCCAGAGCCTTAAGGGGTGACCTGCCGGTGACGGGATGAGGGGTATTCCTAGATTGCTCTATCTACTGGGCTGAAACACTTACTACCTATCTGCCACGAGCCGAGGATAGTCTTTCTGCAAGTTGTTCTTCTTCGGTCGTGAGCTTTGCTACTGATGCATCAGTTGTTCTTTCATGATTCGGATCAATGCTGCTAGATAAAAGATTACAGATCAGCCAACATTGTAGGGGTTGAGACCGGCGCCTTGCTACATGCCCCCCCATGGACACCCCTTCACTAATCGAGAGGGCTTGGAGAACGAGGCACCGCTGATCGGGTCCGCCAGCTGTAGTGTTAAGATCGACTGCTACCTTTTGACATTCTA'
dnaT = 'GCAACAGCTCTTTGCTTGACTCGCATAATGATCCGCGTCCGCACGGCGCGGGTCTCGGTTCCCAATCACAGA'

pos = 0                                    
Motif = []                             
for nucT in range(len(dnaT)):                    
    for nucS in range(pos, len(dnaS)):           
        pos += 1                           
        if len(Motif) < len(dnaT):        
            if dnaT[nucT] == dnaS[nucS]:               
                Motif.append(pos)      
                break                      
print(*Motif, sep = ' ')     