dna1 = 'GCTGTGTAGGGACTCAAGTGTCCGCTGCACTGCGGCTTGGAGCACCCAGCCCTGCTGTTGCACCAAAAACTGAGACGCCCCCGGCTTGTGCCCATCGCCTGATTCGCTAGTAGCTGCCGCTCATATGTGCGCTAGTGCCGATCTACTGAGCCATGTTTAACTCGTGAAATAACGGTACACCGTTGGAGCGATGCTTGCCGCTTCTAGTACTTGACCATTTTGGTCCTAATTGCCTGCTAGTGATATGTGGGGAGATGATATAGATAGTACACACGGCAGATTGAATTCATAAAAAGAGGTCAGACTATCCTCAGGACTCTTTCGGGAAGTTCACAGACCGATCTAGTCACGGTACAAGCTACCGACGCTACATAAAACGTTATTTCCTCTCACTGCCAAAACGATCAAGCAATTTGTCCACTGGCGATTACGTCCAAGGGTATACGAAGTTGGTAGAACCCACCTGCTCTAAGACCTCTAGTCGCCACTCCCTATCAATTAGTTGGGTCAACAATGCTCTACTGAAGTTGCCTTTTGCATTTAGGAGCGCCGACAGAGCATATGTAGCTATCTATCATAGCTTTTCGTCTGTTACTCGAGATGGTAAGGTCGACGCTCCAGGTACAAACGAGTATTTTGCGGCCGCGTTCATTCACGCGGTTACGGCCATCAGCTGGATGAAGATAACACATACGCTATCGCGCTACTCTGGGCACGGGAGTGCTCCCAGGAAGAATATGAAACTCACCTCTGGTACTCGTACTGAACGCGAACAACGGTGGTTTTATAGAGTCAGCGCCAACAACGTGTAGTCTCACAACAAGAAACTAAGCAGCATCATGTAGCCGGTGGCAACTCATTCGTTAAGAAGTTATACTGGACTCTGAGACCCGTGGCAGAACATTGTAGATTAGGGAACTCTAGACCCGAGCCGCATGCGAGTAGCCGGGGCTCAGAGGGTATCCTCATGGTCGCTCTATCCATCATCCA'
dna2 = 'GCTGTGCACATTCGCATGTATTCGACGCACTGCGGCTCTAACCACCTACCCCTGTTGTTGCGCCAAAAATCAAGCTGCTCCCGGCTTGGATTCACGGCCATATTTGCTAATATCTGCCCTTCTCATGTATAACAATGCTGGTCTACTGAGTCAGGTTTAACTTGCGAGCTGACGACCTTCTGTCAAAGTGGAGTTCGCCGCTTCTAGCATTTGACTGTGTTAGTCCTATCCGCTTGCTCGTGATTTGCAGGGAAACGACAGAGATAGTAAGCACGGCAAATTGGACTCGTGCAGAGAGACCGGGTTACCCTCAGGAATCTTTTAAGTAGTCCGTTGATCGATTTAGTCACAGTACGGGCTACTGATACTACATAGAACGTAATTTCCTCTTACTACCTAATCGCTCAAACAATGTACTCACTGGCACTTATAACCAAGAGTATACGAAGCTGGTAGAACCTAGCCGCGTTAAGGCCTGCGGTTACTAACCGCCGTCGGTCGATTGGATTAGCAATAGCTTAGCGAAATTGCCTTCTTCACTTAGTGGGGCTAACAGAGCATATGTAGCTGGCCGTCATAGCCCTCCGTCTGTGACTCGAGATGGTAAGACCTACGCTCCCGGTACTTATTAGTGTTTTGCGGCTCAGACTGGTTACACGGGTGTGCCCGCCACCTGAGTGGAGATAGCGCATGCCTAATCGCGCCTCTTCGTTAACGTGGGTGCTCCCAGGAGGCCTGCGAAGCTTTCCTCCGATGCCCATTCCAAGCGTGACCAATGGTAGCTCTATGGGGTCGGCGCTAGCAACGTATGGTCGTGTGATACGAGATTGAAAAGCACCATATAGCCGGTAGCAATTCACACGAGCAGGAGCTATACCGGGCTCTGGGAGTCAAGGCAGAACATCGCGGGTTAGGGAAATGTTGTTACGAGCCGTATGCGAGTAGCCAGGGTTCAGAGGGTATCTTGACGCACACTCTTCCCATCGTCCA'

transition = 0
transvertion = 0

n = 0

for nucleotide in dna1:
    if nucleotide!= dna2[n]:
        if nucleotide == 'A' and dna2[n] == 'G':
            transition += 1
        elif nucleotide == 'G' and dna2[n] == 'A':
            transition += 1
        elif nucleotide == 'T' and dna2[n] == 'C':
            transition += 1
        elif nucleotide == 'C' and dna2[n] == 'T':
            transition += 1
        
        else:
            transvertion += 1

    n += 1
ratio =  transition / transvertion

print(ratio)
